# custom `Makefile` ###################################
# FastApi custom commands
.PHONY: fastapi-run

fastapi-run:
	export PYTHONPATH=$(PWD) && python app/main.py
# //###################################################
